/// <reference lib="webworker" />
import { clientsClaim, skipWaiting } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

const imageCacheStrategy = new CacheFirst({
  cacheName: 'images-cache',
  plugins: [
    new CacheableResponsePlugin({
      statuses: [0, 200],
    }),
    new ExpirationPlugin({
      maxEntries: 120,
      maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
    }),
  ],
});

// Use prompt-based updates: activate new SW only after SKIP_WAITING message.
clientsClaim();

const normalizePrecacheUrl = (entry: string | { url: string }) => {
  const rawUrl = typeof entry === 'string' ? entry : entry.url;
  const parsed = new URL(rawUrl, self.location.origin);
  parsed.searchParams.delete('__WB_REVISION__');
  return `${parsed.pathname}${parsed.search}${parsed.hash}`;
};

const dedupePrecacheManifest = (manifest: Array<string | { url: string; revision?: string | null }>) => {
  const unique = new Map<string, string | { url: string; revision?: string | null }>();
  for (const entry of manifest) {
    const key = normalizePrecacheUrl(entry);
    const existing = unique.get(key);
    if (!existing || (typeof existing === 'string' && typeof entry !== 'string')) {
      unique.set(key, entry);
    }
  }
  return [...unique.values()];
};

// Precache all static assets generated by the build
precacheAndRoute(dedupePrecacheManifest(self.__WB_MANIFEST));

// App shell routing - serve index.html for navigation requests
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler, {
  denylist: [/^\/api\//, /^\/auth\//], // Exclude API routes if any
});
registerRoute(navigationRoute);

// Cache images with a Cache First strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  imageCacheStrategy
);

// Cache fonts with a Cache First strategy
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// Cache JSON game data and other static data files for offline play
registerRoute(
  ({ request, url }) =>
    request.destination === '' &&
    (url.pathname.endsWith('.json') || url.pathname.startsWith('/assets/')),
  new CacheFirst({
    cacheName: 'data-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 80,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Network first for API calls (if you add them later)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
);

// Stale While Revalidate for other requests
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Listen for messages from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    skipWaiting();
  }
});
