/// <reference lib="webworker" />
import { clientsClaim, skipWaiting } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

const OFFLINE_IMAGE_ASSETS = [
  '/assets/splendor-splash.png',
  '/assets/screenshot-desktop.png',
  '/assets/screenshot-mobile.png',
  '/assets/cards/level1/diamond.png',
  '/assets/cards/level1/emerald.png',
  '/assets/cards/level1/onyx.png',
  '/assets/cards/level1/ruby.png',
  '/assets/cards/level1/sapphire.png',
  '/assets/cards/level2/diamond.png',
  '/assets/cards/level2/emerald.png',
  '/assets/cards/level2/onyx.png',
  '/assets/cards/level2/ruby.png',
  '/assets/cards/level2/sapphire.png',
  '/assets/cards/level3/diamond.png',
  '/assets/cards/level3/emerald.png',
  '/assets/cards/level3/onyx.png',
  '/assets/cards/level3/ruby.png',
  '/assets/cards/level3/sapphire.png',
  '/assets/nobles/anne-brittany.png',
  '/assets/nobles/catherine-medici.png',
  '/assets/nobles/charles-v.png',
  '/assets/nobles/cosimo-medici.png',
  '/assets/nobles/elisabeth-austria.png',
  '/assets/nobles/francis-i.png',
  '/assets/nobles/henry-viii.png',
  '/assets/nobles/isabella-castile.png',
  '/assets/nobles/mary-stuart.png',
  '/assets/nobles/suleiman-magnificent.png',
];

const imageCacheStrategy = new CacheFirst({
  cacheName: 'images-cache',
  plugins: [
    new CacheableResponsePlugin({
      statuses: [0, 200],
    }),
    new ExpirationPlugin({
      maxEntries: 120,
      maxAgeSeconds: 60 * 24 * 60 * 60, // 60 days
    }),
  ],
});

// Use prompt-based updates: activate new SW only after SKIP_WAITING message.
clientsClaim();

// Precache all static assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Warm image cache through the same Workbox strategy used at runtime.
self.addEventListener('install', (event) => {
  event.waitUntil(
    Promise.all(
      OFFLINE_IMAGE_ASSETS.map(async (assetUrl) => {
        const request = new Request(assetUrl, { credentials: 'same-origin' });
        const [, done] = imageCacheStrategy.handleAll({ event, request });
        await done;
      })
    )
  );
});

// App shell routing - serve index.html for navigation requests
const handler = createHandlerBoundToURL('/index.html');
const navigationRoute = new NavigationRoute(handler, {
  denylist: [/^\/api\//, /^\/auth\//], // Exclude API routes if any
});
registerRoute(navigationRoute);

// Cache images with a Cache First strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  imageCacheStrategy
);

// Cache fonts with a Cache First strategy
registerRoute(
  ({ request }) => request.destination === 'font',
  new CacheFirst({
    cacheName: 'fonts-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 20,
        maxAgeSeconds: 365 * 24 * 60 * 60, // 1 year
      }),
    ],
  })
);

// Cache JSON game data and other static data files for offline play
registerRoute(
  ({ request, url }) =>
    request.destination === '' &&
    (url.pathname.endsWith('.json') || url.pathname.startsWith('/assets/')),
  new CacheFirst({
    cacheName: 'data-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 80,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 days
      }),
    ],
  })
);

// Network first for API calls (if you add them later)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-cache',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 5 * 60, // 5 minutes
      }),
    ],
  })
);

// Stale While Revalidate for other requests
registerRoute(
  ({ request }) =>
    request.destination === 'script' ||
    request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Listen for messages from the app
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    skipWaiting();
  }
});
